---
title: "Sarah"
format: html
editor: visual
---

```{r setup}
source(here::here("R/functions-Sarah.R"))
source(here::here("R/functions-Mikkel.R"))
```

```{r}
survey_result <- readr::read_csv(here::here("data-raw/nurses-stress/survey-results.csv"), show_col_types = FALSE)

data_files <- here::here("data-raw/nurses-stress/") |> 
  fs::dir_ls(regexp = "TEMP\\.parquet", recurse = TRUE)

arrow::read_parquet(data_files[4])

```

```{r}
import_dime <- function(file_path) {
  data <- file_path |>
   arrow::read_parquet(
    )
  return(data)
}
```

```{r eval=FALSE}
import_TEMP <- function(folder_path) {
  data_files <- here::here(folder_path) |>
    fs::dir_ls(regexp = "TEMP\\.parquet", recurse = TRUE)
  data <- data_files |>
    purrr::map(arrow::read_parquet) |>
    purrr::list_rbind(names_to = "file_path_id") |>
    dplyr::slice_head(n = 1000)
  return(data)
}

import_TEMP("data-raw/nurses-stress/")
```

```{r}
import_XX <- function(folder_path, format) {
  data_files <- here::here(folder_path) |>
    fs::dir_ls(regexp = paste0(format, "\\.parquet"), recurse = TRUE)
  data <- data_files |>
    purrr::map(arrow::read_parquet) |>
    purrr::list_rbind(names_to = "file_path_id") |>
    dplyr::slice_head(n = 1000)
  return(data)
}

import_XX("data-raw/nurses-stress/", "BVP")
```

```{r}
get_participant_id <- function(data_files) {
  data1 <- data_files |>
    dplyr::mutate(
      id = stringr::str_extract(
        file_path_id, "[:digit:]+\\_[:digit:]") |>
        stringr::str_remove("\\_[:digit:]$") |>
        as.integer(),
      .before = file_path_id
    ) |>
    dplyr::select(-file_path_id)

  return(data1)
}
```

```{r}
import_XX("data-raw/nurses-stress/", "BVP") |>
get_participant_id()
```

```{r}
prepare_dates <- function(data, column) {
  prepared_dates <- data |>
    dplyr::mutate(
      date = lubridate::as_date({{ column }}),
      hour = lubridate::hour({{ column }}),
      .before = {{ column }}
    )
  return(prepared_dates)
}
```

